// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwmoR8ocO6rXPuxwyU0yOQZmc_a0Nd3H4',
    appId: '1:267612126842:android:33a7b40b15b96272fbc5c3',
    messagingSenderId: '267612126842',
    projectId: 'goods-for-exchange',
    databaseURL: 'https://goods-for-exchange-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'goods-for-exchange.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtyMm6CnG7s_6y633dXqO6nrAZgfFJ-zQ',
    appId: '1:267612126842:web:42c36f24e6c238b0fbc5c3',
    messagingSenderId: '267612126842',
    projectId: 'goods-for-exchange',
    authDomain: 'goods-for-exchange.firebaseapp.com',
    databaseURL: 'https://goods-for-exchange-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'goods-for-exchange.appspot.com',
    measurementId: 'G-EJ2K3M25TG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6V204AdKsisTW7J4lxqTo62l_KJ5eiJw',
    appId: '1:267612126842:ios:010ee70e66523af9fbc5c3',
    messagingSenderId: '267612126842',
    projectId: 'goods-for-exchange',
    databaseURL: 'https://goods-for-exchange-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'goods-for-exchange.appspot.com',
    iosBundleId: 'com.planck.goods',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6V204AdKsisTW7J4lxqTo62l_KJ5eiJw',
    appId: '1:267612126842:ios:b98c262a1bb76e73fbc5c3',
    messagingSenderId: '267612126842',
    projectId: 'goods-for-exchange',
    databaseURL: 'https://goods-for-exchange-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'goods-for-exchange.appspot.com',
    iosBundleId: 'com.example.goods',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtyMm6CnG7s_6y633dXqO6nrAZgfFJ-zQ',
    appId: '1:267612126842:web:ea8897ccbf2570c6fbc5c3',
    messagingSenderId: '267612126842',
    projectId: 'goods-for-exchange',
    authDomain: 'goods-for-exchange.firebaseapp.com',
    databaseURL: 'https://goods-for-exchange-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'goods-for-exchange.appspot.com',
    measurementId: 'G-DBJZBVV3PL',
  );

}